### ISSUE TITLE
Is there a way for `spotify play` to actually play songs after a while of not listening. 

### ISSUE THREAD

**Issue by ghost** [ledesmablt/spotify-cli#10]
Every time I pause the music and leave it for more than a few minutes, then try to press play again, Spotify-cli says: 

`Error: No playback session detected
Please start Spotify on one of your devices`

This happens when I do have Spotify app open in my Macbook. So the question is, is there any way to avoid this? Could I add some functionality to the library using a library or is there a simple trick already in the package that avoids this? 

<img width="385" alt="Screen Shot 2021-01-23 at 16 44 47" src="https://user-images.githubusercontent.com/29745063/105616145-5063da00-5d9a-11eb-953f-2d0ba1dbb9e9.png">

**Comment by ledesmablt** [comment]
Hi @PonyKillerMX , I believe this has to do with the Spotify player on your device becoming "inactive" after not playing music for a while. A simple workaround I can think of is sending a "set volume" command periodically if you want to keep it active, that way you'd still be "interacting" with the device while not doing anything too obtrusive.
