### ISSUE TITLE
Spotify API - 400 Bad Request

### ISSUE THREAD

**Issue by Nuckerr** [ledesmablt/spotify-cli#13]
When I run `spotify play --uri https://open.spotify.com/track/71HjxIPItGd2tRkUrBSP5T?si=766408e917094a1e` or any song uri for that matter, it gives me ` Error: Spotify API - 400 Bad Request`. I'm running this in windows 10 powershell in administrator mode

**Comment by ledesmablt** [comment]
Hi @Nuckerr , a Spotify track's URI is different from its URL (which is what you provided). The URI should look something like this - `spotify:track:<track ID>`

You can read more about it [here](https://community.spotify.com/t5/FAQs/What-s-a-Spotify-URI/ta-p/919201).
