### ISSUE TITLE
Can't log in with client id + secret

### ISSUE THREAD

**Issue by arudp** [ledesmablt/spotify-cli#17]
I'm encountering this issue while running the command:
```
$ spotify auth login --client-id XXXXX --client-secret YYYYY
```

The set up starts normally (can choose the options I want to allow), but then, at the moment of going to the auth link `https://accounts.spotify.com/authorize?...` the page just states _INVALID_CLIENT: Invalid redirect URI_ so it's not possible to go further in the auth process.

TBH I don't know if this is an issue with Spotify itself or if it's a bug, but I wanted to bring attention to it, because this cli looks great!

**Comment by ledesmablt** [comment]
Hi @arudp the CLI instructions state that you should "ensure that the URL below is listed as a valid redirect URI in your Spotify application"

https://asia-east2-spotify-cli-283006.cloudfunctions.net/auth-redirect

Please see the screenshot as an example for setting it up. I tried running the command with this set up and it works fine for me.

![image](https://user-images.githubusercontent.com/22242264/122066855-ad355f00-ce25-11eb-9c22-aa1a4c359121.png)

**Comment by arudp** [comment]
Oh god, that was an easy one. Sorry, my bad! Great job!

**Comment by demure** [comment]
Is there any particular reason that there isn't a client (spotify-cli) option to change the URI to a more user local instance?

**Comment by ledesmablt** [comment]
hey @demure i figured that there's no significant gain to adding that option since the redirect url i set up works fine (unless i'm missing something)
