### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'case_sensitive' ?

### ISSUE THREAD

**Issue by ivyturner** [ledesmablt/spotify-cli#24]
whenever i do any commands, this error gets spat out.
already tried re-installing and i dont know how to fix it?

➜ ~ spotify
Traceback (most recent call last):
  File "/home/la/.local/bin/spotify", line 5, in <module>
    from cli.spotify import cli
  File "/home/la/.local/lib/python3.8/site-packages/cli/spotify.py", line 7, in <module>
    from cli.commands.play import play
  File "/home/la/.local/lib/python3.8/site-packages/cli/commands/play.py", line 28, in <module>
    type=click.Choice(['on', 'off'], case_sensitive=False),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'

![image](https://user-images.githubusercontent.com/63261955/164111845-77b8c2a6-4ae1-4b39-b916-0dc0a375d98b.png)

**Comment by ledesmablt** [comment]
hello! strange, looks like `click.Choice` is not recognizing the `case_sensitive` argument even though it exists (see [here](https://github.com/pallets/click/blob/14472ffcd80dd86d47ddc08341168152540ee6f2/src/click/types.py#L244))

can you run `pip3 freeze | grep click` and send the version? my click version is `8.0.3` and spotify-cli is working fine.

**Comment by ivyturner** [comment]
im running click 6.7 so thats probably why, updating now :)

**Comment by ivyturner** [comment]
and fixed :)) thank you for your help

![image](https://user-images.githubusercontent.com/63261955/164911007-ae0c0746-1b5d-4d08-a84d-c8ddd85c4c36.png)
