### ISSUE TITLE
case_sensitive and import errors after installing

### ISSUE THREAD

**Issue by abhivemp** [ledesmablt/spotify-cli#9]
After using `pip install` I tried calling the `spotify` and that's what I got. 

Is there a dependency I am missing? 
```
Traceback (most recent call last):
  File "/home/abhivemp/.local/bin/spotify", line 5, in <module>
    from cli.spotify import cli
  File "/home/abhivemp/.local/lib/python3.6/site-packages/cli/spotify.py", line 7, in <module>       
    from cli.commands.play import play
  File "/home/abhivemp/.local/lib/python3.6/site-packages/cli/commands/play.py", line 28, in <module>
    type=click.Choice(['on', 'off'], case_sensitive=False),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
```
I am using git bash on Win10. I assume that isn't the issue

**Comment by ledesmablt** [comment]
Hi @abhivemp , thanks for raising this issue. What version of `click` are you running this with? I developed this with version 7.0, so maybe this doesn't work with certain older versions. Thanks!

**Comment by abhivemp** [comment]
I don't have `click`. I double-checked by running `click` in my shell.

**Comment by ledesmablt** [comment]
Sorry, i meant the python click package. Try running `pip freeze` and check what version `Click` is here. Thanks!

**Comment by abhivemp** [comment]
Oh sorry @ledesmablt  about that! I have `Click==7.0` 
Do you think I am missing another dependency?

**Comment by ledesmablt** [comment]
Looks like this is related to [this issue](https://github.com/bentoml/BentoML/issues/335) (though I'm also running click 7.0 and it's working fine). Could you try running `pip install -U click` as suggested here and see if it works for you by some chance?

**Comment by abhivemp** [comment]
@ledesmablt that did the trick mate! Thanks for your support!  It actually upgraded my click to 7.1.2 and I am on Windows. I am a bit curious as to how it worked for you with `click==7.0`. Do you think the OS makes a difference? 

Also, I am not too sure if I should open another issue. But in Windows, Spotify provides an alias as spotify.exe. Is there a way I can change that alias to something else so I can run the cli tool AND have the alias? I am aware that I'll have to change the existing alias name. Just not too sure how to do that

**Comment by ledesmablt** [comment]
Awesome :) I'll mark this issue as closed then. I'm running it on WSL Ubuntu, click 7.0.0 worked fine for me. Not sure if there's a compatibility issue at work here.

For your 2nd concern, I believe you have to change the filename of the `spotify` executable for this CLI. Not sure how to do it for windows, but for bash the `which` command works. I think alias conflicts are somewhat uncommon (and maybe expected with small open source projects), but are still manageable through the above solution.

![image](https://user-images.githubusercontent.com/22242264/98467865-af419a80-2212-11eb-8e39-83030f287b59.png)

Please let me know if this helps. Thanks!
